module: run_eval

seed: 0

eval_data:
  dataset_name: dl3dv
  dataset_name_log: dl3dv_6_view_posed
  zero_out_cam_cond_p: 0.0
  # Path to test view indices JSON file.
  # We provide 2v, 4v, and 6v splits in assets/
  test_view_indices_path: ./assets/dl3dv_6v.json
  num_cond_views: 6
  video_path_type: bspline_interp_eased

model:
  arch: 'EncDecVitB/8'
  attention_to_features_type: bidirectional_cross_attention

opt:
  batch_size: 512

data:
  im_size_hw:
  - 256
  - 256
  eval_video_length: 100

# Checkpoint is auto-downloaded from HuggingFace on first run.
checkpoint_path: hf://facebook/lagernvs_dl3dv_2-6_v_256/model.pt

log_dir: ./output
